### ISSUE TITLE
The tool does not support parsing the ICMP protocol

### ISSUE THREAD

**Issue by CSUer2021** [vs-uulm/fieldhunter#2]
hello, I used the tool to parse the icmp protocol and set the parameter for layer to 1, but it doesn't parse the fields properly, and the error is as follows：
TypeError: To identify flows, all messages need to be from a known encapsulation with known network and transport layer protocols. No flow determined for L3NetworkMessage:
[1106520836.93609 24.6.126.218->198.173.244.32] '\x08\x00òÿ\x02\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

**Comment by skleber** [comment]
This is an inherent limitation of the FieldHunter (FH) approach. It requires a flow to be identified for each packet to be able to work. The error message states "To identify flows, all messages need to be from a known encapsulation with known network and transport layer protocols.", which basically explains exactly this: In FH, a flow is defined by the 5-tuple: Layer-4 Protocol, Source IP, Destination IP, Source Port, Destination Port (FH, Section2, Footnote 1).
Below ICMP, there is no network layer (TCP/UDP). So FH will never work on this type of protocol.

For further questions about the underlying method refer to the original FH paper or contact the paper authors: https://github.com/vs-uulm/fieldhunter/blob/master/README.md
